import type { Negocio } from "./airtable";

/**
 * Datos de ejemplo, solo para fines ilustrativos mientras Airtable no está
 * conectado (o mientras la base todavía no tiene negocios reales). En cuanto
 * AIRTABLE_API_KEY / AIRTABLE_BASE_ID estén configurados y la consulta a
 * Airtable funcione, estos datos dejan de usarse automáticamente — ver el
 * try/catch en cada función de lib/airtable.ts.
 */
export const SAMPLE_NEGOCIOS: Negocio[] = [
  {
    id: "sample-mariscos-el-guamuchil",
    nombre: "Mariscos El Guamúchil",
    slug: "mariscos-el-guamuchil",
    categoria: "Restaurantes",
    descripcionCorta: "Mariscos frescos estilo Sinaloa",
    descripcionLarga:
      "Desde 2015 servimos mariscos frescos de la costa de Sinaloa: aguachiles, ceviches y pescado zarandeado preparado al carbón todos los días. Ambiente familiar, ideal para comer en grupo.",
    logoUrl:
      "https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?auto=format&fit=crop&w=300&q=80",
    fotoPortadaUrl:
      "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?auto=format&fit=crop&w=1000&q=85",
    estado: "destacado",
    telefono: "6681234501",
    whatsapp: "6681234501",
    direccion: "Blvd. Rosendo G. Castro 1450, Zona Dorada, Los Mochis, Sinaloa",
    instagram: "@mariscoselguamuchil",
    facebook: "MariscosElGuamuchilLosMochis",
    horarios: "Lun-Dom 12:00pm - 10:00pm",
    galeria: [
      "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=600&q=80",
      "https://images.unsplash.com/photo-1625944230945-1b7dd3b949ab?auto=format&fit=crop&w=600&q=80",
      "https://images.unsplash.com/photo-1585238342024-78d387f4a707?auto=format&fit=crop&w=600&q=80",
    ],
    menu: [
      { nombre: "Aguachile verde", descripcion: "Camarón fresco, pepino, cebolla morada, chile serrano", precio: "$180" },
      { nombre: "Ceviche de camarón", descripcion: "Limón, jitomate, cilantro, aguacate", precio: "$150" },
      { nombre: "Tostadas de ceviche (3 pzas)", descripcion: "Ceviche de camarón sobre tostada crujiente", precio: "$95" },
      { nombre: "Camarones a la diabla", descripcion: "Picante, con arroz y ensalada", precio: "$210" },
      { nombre: "Pescado zarandeado (media orden)", descripcion: "Sazonado y asado al carbón", precio: "$240" },
      { nombre: "Coctel de camarón chico", descripcion: "Clásico coctel estilo Sinaloa", precio: "$120" },
      { nombre: "Chicharrón de camarón", descripcion: "Botana crujiente con salsa", precio: "$160" },
      { nombre: "Michelada El Guamúchil", descripcion: "Cerveza clara preparada", precio: "$75" },
    ],
    addonWhatsapp: true,
    addonMapas: true,
    addonGaleria: true,
    addonFormularioContacto: false,
    addonPedidos: true,
    addonReservaciones: true,
    addonQrMesa: false,
    addonLealtad: false,
    addonMultiSucursal: false,
  },
  {
    id: "sample-rincon-del-cafe",
    nombre: "Rincón del Café",
    slug: "rincon-del-cafe",
    categoria: "Cafeterías",
    descripcionCorta: "Café de especialidad · Centro",
    descripcionLarga:
      "Café de especialidad tostado localmente, repostería casera y un rincón tranquilo en pleno Centro de Los Mochis para trabajar, leer o platicar con calma.",
    logoUrl:
      "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=300&q=80",
    fotoPortadaUrl:
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1000&q=85",
    estado: "destacado",
    telefono: "6681234502",
    whatsapp: "6681234502",
    direccion: "Ignacio Zaragoza 320, Centro, Los Mochis, Sinaloa",
    instagram: "@rincondelcafe.mochis",
    facebook: "RincondelCafeLosMochis",
    horarios: "Lun-Sáb 7:30am - 9:00pm · Dom 8:00am - 3:00pm",
    galeria: [
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=80",
      "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=600&q=80",
      "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=600&q=80",
    ],
    menu: [
      { nombre: "Café de olla", descripcion: "Canela, piloncillo", precio: "$45" },
      { nombre: "Cappuccino", descripcion: "Doble shot", precio: "$55" },
      { nombre: "Latte de vainilla", descripcion: "Espresso, leche vaporizada, vainilla", precio: "$58" },
      { nombre: "Cold brew", descripcion: "12 horas de extracción en frío", precio: "$60" },
      { nombre: "Pan dulce del día", descripcion: "Recién horneado", precio: "$30" },
      { nombre: "Concha rellena de nata", descripcion: "Clásico mexicano", precio: "$38" },
      { nombre: "Croissant de jamón y queso", descripcion: "Horneado al momento", precio: "$52" },
      { nombre: "Chai latte", descripcion: "Especias, leche vaporizada", precio: "$56" },
    ],
    addonWhatsapp: true,
    addonMapas: true,
    addonGaleria: true,
    addonFormularioContacto: false,
    addonPedidos: false,
    addonReservaciones: false,
    addonQrMesa: true,
    addonLealtad: true,
    addonMultiSucursal: false,
  },
  {
    id: "sample-tacos-el-guero",
    nombre: "Tacos El Güero",
    slug: "tacos-el-guero",
    categoria: "Snacks",
    descripcionCorta: "Antojitos · Centro",
    descripcionLarga:
      "Tacos de asada y adobada al estilo Sinaloa desde hace más de 10 años. Ya somos 3 sucursales en Los Mochis por la demanda de nuestros clientes.",
    logoUrl:
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=300&q=80",
    fotoPortadaUrl:
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=1000&q=85",
    estado: "destacado",
    telefono: "6681234503",
    whatsapp: "6681234503",
    direccion: "Av. Álvaro Obregón 88, Centro, Los Mochis, Sinaloa",
    instagram: "@tacoselguero.mochis",
    facebook: "TacosElGueroLosMochis",
    horarios: "Lun-Dom 6:00pm - 1:00am",
    galeria: [
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80",
      "https://images.unsplash.com/photo-1615870216519-2f9fa575fa5c?auto=format&fit=crop&w=600&q=80",
      "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?auto=format&fit=crop&w=600&q=80",
    ],
    menu: [
      { nombre: "Taco de asada", descripcion: "Carne asada, cebolla, cilantro", precio: "$22" },
      { nombre: "Taco de adobada", descripcion: "Trompo estilo Sinaloa", precio: "$20" },
      { nombre: "Taco de camarón", descripcion: "Empanizado, con aderezo", precio: "$28" },
      { nombre: "Quesotaco", descripcion: "Con queso derretido", precio: "$25" },
      { nombre: "Orden de papas El Güero", descripcion: "Con queso y tocino", precio: "$65" },
      { nombre: "Vampiro", descripcion: "Tostada con carne y queso gratinado", precio: "$30" },
      { nombre: "Dorilocos chicos", descripcion: "Con elote, chamoy y dulces", precio: "$45" },
      { nombre: "Agua fresca de horchata", descripcion: "500 ml", precio: "$25" },
    ],
    addonWhatsapp: true,
    addonMapas: true,
    addonGaleria: false,
    addonFormularioContacto: false,
    addonPedidos: true,
    addonReservaciones: false,
    addonQrMesa: false,
    addonLealtad: false,
    addonMultiSucursal: true,
  },
  {
    id: "sample-dulce-pecado",
    nombre: "Dulce Pecado",
    slug: "dulce-pecado",
    categoria: "Panaderías",
    descripcionCorta: "Repostería · Centro",
    descripcionLarga:
      "Repostería artesanal: pasteles, cheesecakes y pan dulce horneados diario. También hacemos pasteles personalizados para cumpleaños y eventos — escríbenos con tiempo.",
    logoUrl:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=300&q=80",
    fotoPortadaUrl:
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1000&q=85",
    estado: "destacado",
    telefono: "6681234504",
    whatsapp: "6681234504",
    direccion: "Guillermo Prieto 210, Jiquilpan, Los Mochis, Sinaloa",
    instagram: "@dulcepecado.mochis",
    facebook: "DulcePecadoLosMochis",
    horarios: "Mar-Dom 9:00am - 8:00pm · Lun cerrado",
    galeria: [
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80",
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80",
      "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?auto=format&fit=crop&w=600&q=80",
    ],
    menu: [
      { nombre: "Pastel de tres leches (rebanada)", descripcion: "Clásico, con canela", precio: "$55" },
      { nombre: "Cheesecake de zarzamora", descripcion: "Cremoso, con mermelada de zarzamora", precio: "$60" },
      { nombre: "Concha grande", descripcion: "Cobertura de vainilla o chocolate", precio: "$28" },
      { nombre: "Cuernito relleno de crema", descripcion: "Recién horneado", precio: "$32" },
      { nombre: "Brownie de chocolate", descripcion: "Con nuez", precio: "$38" },
      { nombre: "Galletas de avena (2 pzas)", descripcion: "Con chispas de chocolate", precio: "$25" },
      { nombre: "Pay de limón (rebanada)", descripcion: "Costra crujiente, relleno cremoso", precio: "$50" },
      { nombre: "Pastelillo de fresa", descripcion: "Individual, con crema batida", precio: "$35" },
    ],
    addonWhatsapp: true,
    addonMapas: true,
    addonGaleria: true,
    addonFormularioContacto: true,
    addonPedidos: false,
    addonReservaciones: false,
    addonQrMesa: false,
    addonLealtad: false,
    addonMultiSucursal: false,
  },
];
